FROM node:14.8.0-alpine3.12

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node package*.json ./

RUN npm install

COPY --chown=node ./ .

RUN npm run build

EXPOSE 3000

USER node

CMD ["npm", "run", "start:prod"]